name: dependency-review

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    uses: kenny-amp/.github/.github/workflows/reusable-dependency-review.yml@main
